version: "1"

volumes:
  db-data:
    external: false

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:cached
    ports:
      - 13306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
  php-fpm:
    build: ./docker/php-fpm
    container_name: maxcomply-fpm-php
    environment:
      - SYMFONY_DEBUG=true
      - SYMFONY_ENV=dev
    depends_on:
      - db
    volumes:
      - .:/app:cached
    ports:
      - 2080:8080
  maxcomply.local:
    image: nginx:1.11.10
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 80:80
