parameters:
    locale: en
    base_url: '%env(BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/{Services,Repository}'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]
